# NumPy

NumPy is the fundamental library for scientific computing with Python. It contains many useful features:

- a powerful N-dimensional array object
- sophiticasted (broadcasting functions)
- tools for integrating C/C++ and Fortran code
- userful linear algebra, Fouries transform, and random number capabilities

Library documentation: [http://www.numpy.org/](http://www.numpy.org/)

In this notebook, I do some experiments with NumPy library.

In [2]:
import numpy as np

In [3]:
# declare a vector using a list as the argument
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [4]:
# declare a matrix using a nested list as the argument
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [5]:
# v and M have same type but with different shapes
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [6]:
v.size, M.size

(4, 4)

In [7]:
# create an array with start, stop and step
x = np.arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# create an array with 20 items from 0 to 10
y = np.linspace(0, 10, 20)
y

array([  0.        ,   0.52631579,   1.05263158,   1.57894737,
         2.10526316,   2.63157895,   3.15789474,   3.68421053,
         4.21052632,   4.73684211,   5.26315789,   5.78947368,
         6.31578947,   6.84210526,   7.36842105,   7.89473684,
         8.42105263,   8.94736842,   9.47368421,  10.        ])

In [10]:
# create an array on log scale
z = np.logspace(0, 10, 10, base=e)
z

array([  1.00000000e+00,   3.03773178e+00,   9.22781435e+00,
         2.80316249e+01,   8.51525577e+01,   2.58670631e+02,
         7.85771994e+02,   2.38696456e+03,   7.25095809e+03,
         2.20264658e+04])

In [11]:
# create a dense multi-dimesional (meshgrid)
a, b = np.mgrid[0:5, 0:5]
a

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [12]:
b

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [13]:
# Experiment with random
from numpy import random

In [16]:
# Createa a random N-dimesional array
M = random.rand(5, 5)
M

array([[ 0.72828134,  0.41363584,  0.63305022,  0.69058335,  0.76834166],
       [ 0.06939728,  0.24127341,  0.0532769 ,  0.81242079,  0.99731098],
       [ 0.25397214,  0.06919239,  0.17310172,  0.37877306,  0.21704294],
       [ 0.66451176,  0.43415963,  0.28058583,  0.72456748,  0.94216747],
       [ 0.74341978,  0.93871677,  0.88768758,  0.44534492,  0.94955033]])

In [17]:
# Createa a diagonal matrix 
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [18]:
M.itemsize

8

In [19]:
M.nbytes

200

In [20]:
M.ndim

2

In [22]:
# Get a row
M[1]

array([ 0.06939728,  0.24127341,  0.0532769 ,  0.81242079,  0.99731098])

In [23]:
# Get an item 
M[0,0]

0.72828134438033021

In [25]:
#Get a column
M[:,0]

array([ 0.72828134,  0.06939728,  0.25397214,  0.66451176,  0.74341978])

In [26]:
# slicing
A = np.array([1,2,3,4,5,6])
A[1:3]

array([2, 3])

In [27]:
A = array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [28]:
row_indices = [1,2,3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [29]:
# index masking
B = array([n for n in range(5)])
row_mask = array([True, False, True, False, False])
B[row_mask]

array([0, 2])

## Linear Algebra

In [30]:
vl = np.arange(0,5)
vl

array([0, 1, 2, 3, 4])

In [32]:
# sum of an array and a scalar
vl + 2

array([2, 3, 4, 5, 6])

In [33]:
# element-wise product with scalar
vl * 2

array([0, 2, 4, 6, 8])

In [34]:
# element-wise product of two array
vl * vl

array([ 0,  1,  4,  9, 16])

In [35]:
# product of two array
np.dot(vl, vl)

30

In [36]:
np.dot(A, vl)

array([ 30, 130, 230, 330, 430])

In [37]:
np.dot(vl, A)

array([300, 310, 320, 330, 340])

In [38]:
# cast to matrix
M = np.matrix(A)
M*M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [40]:
# inner product
v.T * v

array([ 1,  4,  9, 16])

In [41]:
v

array([1, 2, 3, 4])

In [42]:
v * v

array([ 1,  4,  9, 16])

In [43]:
C = matrix([[1j, 2j], [3j, 4j]])
C

matrix([[ 0.+1.j,  0.+2.j],
        [ 0.+3.j,  0.+4.j]])

In [48]:
D = np.conjugate(C)
D

matrix([[ 0.-1.j,  0.-2.j],
        [ 0.-3.j,  0.-4.j]])

In [49]:
C + D

matrix([[ 0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j]])

In [51]:
# inverse
I = C.I
I

matrix([[ 0.+2.j ,  0.-1.j ],
        [ 0.-1.5j,  0.+0.5j]])

In [52]:
C * I

matrix([[  1.00000000e+00+0.j,   1.11022302e-16+0.j],
        [  0.00000000e+00+0.j,   1.00000000e+00+0.j]])

## Statistics

In [54]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [55]:
np.mean(A[:, 3])

23.0

In [56]:
np.std(A[:,3])

14.142135623730951

In [57]:
np.var(A[:,3])

200.0

In [58]:
A[:,3].min()

3

In [59]:
A[:,3].max()

43

In [60]:
# reshape without copying underlying data
n, m = A.shape
B = A.reshape((1,n*m))

B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
        32, 33, 34, 40, 41, 42, 43, 44]])

In [61]:
# modify the array
B[0,0:5] = 5
B

array([[ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
        32, 33, 34, 40, 41, 42, 43, 44]])

In [63]:
# A is also changed
A

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [64]:
# creates a copy
B = A.flatten()
B

array([ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [65]:
# deep copy
C = copy(A)

In [66]:
C

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])